modLoader = "javafml"
loaderVersion = "[47,)"
license = "MIT"

[[dependencies.tallinomod]]
    modId = "forge"
    mandatory = true
    versionRange = "[47,)"
    ordering = "NONE"
    side = "BOTH"

[[dependencies.tallinomod]]
    modId = "minecraft"
    mandatory = true
    versionRange = "[1.20.1,1.21)"
    ordering = "NONE"
    side = "BOTH"

[[mods]]
    modId = "tallinomod"
    version = "1.0.0"
    displayName = "Tallinosaurus Mod"
    description = "Adds the Tallinosaurus, a curious passive dinosaur."
